/* =========================================================
   ESPÓLIO — SUB-TABELAS DE ITENS (TORMENTA20)
   Geradas de: T20 - Tabela de geração de tesouros.xlsx
   ========================================================= */

/* ===== ITENS DIVERSOS ===== */
var ITENS_DIVERSOS = [
  { b: "01", n: "Ácido", l: "Tormenta20", p: 160 },
  { b: "02", n: "Água benta", l: "Tormenta20", p: 155 },
  { b: "03", n: "Alaúde élfico", l: "Tormenta20", p: 158 },
  { b: "04", n: "Algemas", l: "Tormenta20", p: 155 },
  { b: "05", n: "Baga-de-fogo", l: "Tormenta20", p: 160 },
  { b: "06-08", n: "Bálsamo restaurador", l: "Tormenta20", p: 160 },
  { b: "09", n: "Bandana", l: "Tormenta20", p: 159 },
  { b: "10", n: "Bandoleira de poções", l: "Tormenta20", p: 155 },
  { b: "11", n: "Bomba", l: "Tormenta20", p: 160 },
  { b: "12", n: "Botas reforçadas", l: "Tormenta20", p: 159 },
  { b: "13", n: "Camisa bufante", l: "Tormenta20", p: 159 },
  { b: "14", n: "Capa esvoaçante", l: "Tormenta20", p: 159 },
  { b: "15", n: "Capa pesada", l: "Tormenta20", p: 159 },
  { b: "16", n: "Casaco longo", l: "Tormenta20", p: 159 },
  { b: "17", n: "Chapéu arcano", l: "Tormenta20", p: 159 },
  { b: "18", n: "Coleção de livros", l: "Tormenta20", p: 158 },
  { b: "19", n: "Cosmético", l: "Tormenta20", p: 160 },
  { b: "20", n: "Dente-de-dragão", l: "Tormenta20", p: 161 },
  { b: "21", n: "Enfeite de elmo", l: "Tormenta20", p: 159 },
  { b: "22", n: "Elixir do amor", l: "Tormenta20", p: 160 },
  { b: "23", n: "Equipamento de viagem", l: "Tormenta20", p: 155 },
  { b: "24-26", n: "Essência de mana", l: "Tormenta20", p: 160 },
  { b: "27", n: "Estojo de disfarces", l: "Tormenta20", p: 158 },
  { b: "28", n: "Farrapos de ermitão", l: "Tormenta20", p: 159 },
  { b: "29", n: "Flauta mística", l: "Tormenta20", p: 158 },
  { b: "30", n: "Fogo alquímico", l: "Tormenta20", p: 160 },
  { b: "31", n: "Gorro de ervas", l: "Tormenta20", p: 159 },
  { b: "32", n: "Líquen lilás", l: "Tormenta20", p: 161 },
  { b: "33", n: "Luneta", l: "Tormenta20", p: 158 },
  { b: "34", n: "Luva de pelica", l: "Tormenta20", p: 159 },
  { b: "35", n: "Maleta de medicamentos", l: "Tormenta20", p: 158 },
  { b: "36", n: "Manopla", l: "Tormenta20", p: 159 },
  { b: "37", n: "Manto eclesiástico", l: "Tormenta20", p: 159 },
  { b: "38", n: "Mochila de aventureiro", l: "Tormenta20", p: 155 },
  { b: "39", n: "Musgo púrpura", l: "Tormenta20", p: 161 },
  { b: "40", n: "Organizador de pergaminhos", l: "Tormenta20", p: 155 },
  { b: "41", n: "Ossos de monstro", l: "Tormenta20", p: 161 },
  { b: "42", n: "Pó de cristal", l: "Tormenta20", p: 161 },
  { b: "43", n: "Pó de giz", l: "Tormenta20", p: 161 },
  { b: "44", n: "Pó do desaparecimento", l: "Tormenta20", p: 160 },
  { b: "45", n: "Robe místico", l: "Tormenta20", p: 159 },
  { b: "46", n: "Saco de sal", l: "Tormenta20", p: 161 },
  { b: "47", n: "Sapatos de camurça", l: "Tormenta20", p: 159 },
  { b: "48", n: "Seixo de âmbar", l: "Tormenta20", p: 161 },
  { b: "49", n: "Sela", l: "Tormenta20", p: 158 },
  { b: "50", n: "Tabardo", l: "Tormenta20", p: 159 },
  { b: "51", n: "Traje da corte", l: "Tormenta20", p: 159 },
  { b: "52", n: "Terra de cemitério", l: "Tormenta20", p: 161 },
  { b: "53", n: "Veste de seda", l: "Tormenta20", p: 159 },
  { b: "54", n: "Corda de teia", l: "Ameaças de Arton", p: 396 },
  { b: "55", n: "Dente de wisphago", l: "Ameaças de Arton", p: 396 },
  { b: "56", n: "Bomba de fumaça", l: "Ameaças de Arton", p: 396 },
  { b: "57", n: "Elixir quimérico", l: "Ameaças de Arton", p: 396 },
  { b: "58", n: "Éter elemental", l: "Ameaças de Arton", p: 396 },
  { b: "59", n: "Óleo de besouro", l: "Ameaças de Arton", p: 397 },
  { b: "60", n: "Água benta concentrada", l: "Deuses de Arton", p: 48 },
  { b: "61", n: "Aspersório", l: "Deuses de Arton", p: 48 },
  { b: "62", n: "Patuá", l: "Deuses de Arton", p: 49 },
  { b: "63", n: "Panfleto de aforismos", l: "Deuses de Arton", p: 49 },
  { b: "64", n: "Texto sagrado", l: "Deuses de Arton", p: 49 },
  { b: "65", n: "Hábito sacerdotal", l: "Deuses de Arton", p: 49 },
  { b: "66", n: "Manto de alto sacerdote", l: "Deuses de Arton", p: 49 },
  { b: "67", n: "Sandálias", l: "Deuses de Arton", p: 51 },
  { b: "68", n: "Piercing de umbigo", l: "Deuses de Arton", p: 51 },
  { b: "69", n: "Incenso", l: "Deuses de Arton", p: 52 },
  { b: "70", n: "Santa granada de mão", l: "Deuses de Arton", p: 52 },
  { b: "71", n: "Fitilho consagrado", l: "Deuses de Arton", p: 52 },
  { b: "72", n: "Pena de anjo", l: "Deuses de Arton", p: 52 },
  { b: "73", n: "Ábaco", l: "Heróis de Arton", p: 227 },
  { b: "74", n: "Ampulheta", l: "Heróis de Arton", p: 227 },
  { b: "75", n: "Astrolábio", l: "Heróis de Arton", p: 227 },
  { b: "76", n: "Bainha adornada", l: "Heróis de Arton", p: 227 },
  { b: "77", n: "Bússola", l: "Heróis de Arton", p: 227 },
  { b: "78", n: "Diagrama anatômico", l: "Heróis de Arton", p: 230 },
  { b: "79", n: "Estrepes", l: "Heróis de Arton", p: 230 },
  { b: "80", n: "Lampião de foco", l: "Heróis de Arton", p: 230 },
  { b: "81", n: "Leque", l: "Heróis de Arton", p: 230 },
  { b: "82", n: "Lupa", l: "Heróis de Arton", p: 230 },
  { b: "83", n: "Mapa (mestre define de qual região)", l: "Heróis de Arton", p: 230 },
  { b: "84", n: "Mecanismo de mola", l: "Heróis de Arton", p: 230 },
  { b: "85", n: "Mochila discreta", l: "Heróis de Arton", p: 230 },
  { b: "86", n: "Sinete", l: "Heróis de Arton", p: 231 },
  { b: "87", n: "Apito de caça", l: "Heróis de Arton", p: 231 },
  { b: "88", n: "Baralho marcado", l: "Heróis de Arton", p: 231 },
  { b: "89", n: "Clarim deheoni", l: "Heróis de Arton", p: 231 },
  { b: "90", n: "Pandeiro das estradas", l: "Heróis de Arton", p: 231 },
  { b: "91", n: "Camisolão", l: "Heróis de Arton", p: 232 },
  { b: "92", n: "Casaca de apetrechos", l: "Heróis de Arton", p: 232 },
  { b: "93", n: "Chapéu emplumado", l: "Heróis de Arton", p: 232 },
  { b: "94", n: "Elmo leve", l: "Heróis de Arton", p: 232 },
  { b: "95", n: "Elmo pesado", l: "Heróis de Arton", p: 232 },
  { b: "96", n: "Rondel", l: "Heróis de Arton", p: 233 },
  { b: "97", n: "Sapatos confortáveis", l: "Heróis de Arton", p: 233 },
  { b: "98", n: "Sapatos de salto alto", l: "Heróis de Arton", p: 233 },
  { b: "99", n: "Ácido concentrado", l: "Heróis de Arton", p: 234 },
  { b: "100", n: "Frasco abissal", l: "Heróis de Arton", p: 234 },
];

/* ===== EQUIPAMENTOS ===== */
var EQUIPAMENTOS = {
  bloco1: {
    titulo: "ARMAS",
    linhas: [
      { b: "01", n: "Açoite finntroll", l: "Ameaças de Arton", p: 392 },
      { b: "02", n: "Adaga", l: "Tormenta20", p: 146 },
      { b: "03", n: "Adaga oposta", l: "Heróis de Arton", p: 216 },
      { b: "04", n: "Agulha de Ahlen", l: "Heróis de Arton", p: 216 },
      { b: "05", n: "Alabarda", l: "Tormenta20", p: 146 },
      { b: "06", n: "Alfange", l: "Tormenta20", p: 146 },
      { b: "07", n: "Arcabuz", l: "Ameaças de Arton", p: 392 },
      { b: "08", n: "Arco curto", l: "Tormenta20", p: 146 },
      { b: "09", n: "Arco de guerra", l: "Heróis de Arton", p: 216 },
      { b: "10", n: "Arco longo", l: "Tormenta20", p: 146 },
      { b: "11", n: "Arco montado", l: "Heróis de Arton", p: 216 },
      { b: "12", n: "Arpão", l: "Ameaças de Arton", p: 392 },
      { b: "13", n: "Azagaia", l: "Tormenta20", p: 146 },
      { b: "14", n: "Bacamarte", l: "Ameaças de Arton", p: 392 },
      { b: "15", n: "Balas (20)", l: "Tormenta20", p: 151 },
      { b: "16", n: "Balestra", l: "Heróis de Arton", p: 216 },
      { b: "17", n: "Bastão lúdico", l: "Heróis de Arton", p: 216 },
      { b: "18", n: "Besta de mão", l: "Heróis de Arton", p: 216 },
      { b: "19", n: "Besta de repetição", l: "Heróis de Arton", p: 216 },
      { b: "20", n: "Besta dupla", l: "Heróis de Arton", p: 216 },
      { b: "21", n: "Besta leve", l: "Tormenta20", p: 146 },
      { b: "22", n: "Besta pesada", l: "Tormenta20", p: 146 },
      { b: "23", n: "Bico de corvo", l: "Heróis de Arton", p: 216 },
      { b: "24", n: "Boleadeira", l: "Heróis de Arton", p: 216 },
      { b: "25", n: "Bordão", l: "Tormenta20", p: 147 },
      { b: "26", n: "Canhão portátil", l: "Heróis de Arton", p: 217 },
      { b: "27", n: "Chakram", l: "Heróis de Arton", p: 217 },
      { b: "28", n: "Chicote", l: "Tormenta20", p: 147 },
      { b: "29", n: "Cimitarra", l: "Tormenta20", p: 147 },
      { b: "30", n: "Cinquedea", l: "Heróis de Arton", p: 217 },
      { b: "31", n: "Clava", l: "Tormenta20", p: 147 },
      { b: "32", n: "Clava-grão", l: "Heróis de Arton", p: 217 },
      { b: "33", n: "Corrente de espinhos", l: "Tormenta20", p: 147 },
      { b: "34", n: "Desmontador", l: "Heróis de Arton", p: 217 },
      { b: "35", n: "Dirk", l: "Heróis de Arton", p: 217 },
      { b: "36", n: "Espada bastarda", l: "Tormenta20", p: 147 },
      { b: "37", n: "Espada canora", l: "Heróis de Arton", p: 217 },
      { b: "38", n: "Espada curta", l: "Tormenta20", p: 148 },
      { b: "39", n: "Espada de execução", l: "Heróis de Arton", p: 217 },
      { b: "40", n: "Espada larga", l: "Heróis de Arton", p: 217 },
      { b: "41", n: "Espada longa", l: "Tormenta20", p: 148 },
      { b: "42", n: "Espada vespa", l: "Ameaças de Arton", p: 392 },
      { b: "43", n: "Espada-gadanho", l: "Heróis de Arton", p: 217 },
      { b: "44", n: "Espadim", l: "Heróis de Arton", p: 217 },
      { b: "45", n: "Flechas (20)", l: "Tormenta20", p: 151 },
      { b: "46", n: "Flechas de caça (20)", l: "Heróis de Arton", p: 223 },
      { b: "47", n: "Florete", l: "Tormenta20", p: 148 },
      { b: "48", n: "Foice", l: "Tormenta20", p: 148 },
      { b: "49", n: "Funda", l: "Tormenta20", p: 148 },
      { b: "50", n: "Gadanho", l: "Tormenta20", p: 148 },
      { b: "51", n: "Garrucha", l: "Heróis de Arton", p: 219 },
      { b: "52", n: "Gládio", l: "Ameaças de Arton", p: 392 },
      { b: "53", n: "Katana", l: "Tormenta20", p: 148 },
      { b: "54", n: "Khopesh", l: "Heróis de Arton", p: 219 },
      { b: "55", n: "Kimbata", l: "Heróis de Arton", p: 219 },
      { b: "56", n: "Lança", l: "Tormenta20", p: 148 },
      { b: "57", n: "Lança de falange", l: "Heróis de Arton", p: 220 },
      { b: "58", n: "Lança de fogo", l: "Ameaças de Arton", p: 392 },
      { b: "59", n: "Lança de justa", l: "Heróis de Arton", p: 220 },
      { b: "60", n: "Lança montada", l: "Tormenta20", p: 148 },
      { b: "61", n: "Maça", l: "Tormenta20", p: 149 },
      { b: "62", n: "Maça-estrela", l: "Heróis de Arton", p: 220 },
      { b: "63", n: "Machadinha", l: "Tormenta20", p: 149 },
      { b: "64", n: "Machado anão", l: "Tormenta20", p: 149 },
      { b: "65", n: "Machado de batalha", l: "Tormenta20", p: 149 },
      { b: "66", n: "Machado de guerra", l: "Tormenta20", p: 149 },
      { b: "67", n: "Machado de haste", l: "Heróis de Arton", p: 220 },
      { b: "68", n: "Machado táurico", l: "Tormenta20", p: 149 },
      { b: "69", n: "Malho", l: "Heróis de Arton", p: 220 },
      { b: "70", n: "Mangual", l: "Tormenta20", p: 149 },
      { b: "71", n: "Marrão", l: "Heróis de Arton", p: 221 },
      { b: "72", n: "Marreta", l: "Tormenta20", p: 149 },
      { b: "73", n: "Martelo de guerra", l: "Tormenta20", p: 149 },
      { b: "74", n: "Martelo leve", l: "Heróis de Arton", p: 221 },
      { b: "75", n: "Martelo longo", l: "Heróis de Arton", p: 221 },
      { b: "76", n: "Montante", l: "Tormenta20", p: 150 },
      { b: "77", n: "Montante cinético", l: "Heróis de Arton", p: 221 },
      { b: "78", n: "Mordida do diabo", l: "Ameaças de Arton", p: 393 },
      { b: "79", n: "Mosquete", l: "Tormenta20", p: 150 },
      { b: "80", n: "Neko-te", l: "Ameaças de Arton", p: 393 },
      { b: "81", n: "Pedras (20)", l: "Tormenta20", p: 151 },
      { b: "82", n: "Picareta", l: "Tormenta20", p: 150 },
      { b: "83", n: "Pique", l: "Tormenta20", p: 150 },
      { b: "84", n: "Pistola", l: "Tormenta20", p: 150 },
      { b: "85", n: "Pistola-punhal", l: "Ameaças de Arton", p: 393 },
      { b: "86", n: "Porrete", l: "Ameaças de Arton", p: 393 },
      { b: "87", n: "Presa de serpente", l: "Ameaças de Arton", p: 393 },
      { b: "88", n: "Rapieira", l: "Heróis de Arton", p: 221 },
      { b: "89", n: "Rede", l: "Tormenta20", p: 150 },
      { b: "90", n: "Serrilheira", l: "Heróis de Arton", p: 221 },
      { b: "91", n: "Shuriken", l: "Ameaças de Arton", p: 394 },
      { b: "92", n: "Sifão cáustico", l: "Heróis de Arton", p: 222 },
      { b: "93", n: "Tacape", l: "Tormenta20", p: 150 },
      { b: "94", n: "Tai-tai", l: "Heróis de Arton", p: 222 },
      { b: "95", n: "Tan-korak", l: "Heróis de Arton", p: 222 },
      { b: "96", n: "Tetsubo", l: "Ameaças de Arton", p: 394 },
      { b: "97", n: "Traque", l: "Ameaças de Arton", p: 394 },
      { b: "98", n: "Tridente", l: "Tormenta20", p: 150 },
      { b: "99", n: "Virotes (20)", l: "Tormenta20", p: 151 },
      { b: "100", n: "Zarabatana", l: "Ameaças de Arton", p: 394 },
    ]
  },
  bloco2: {
    titulo: "ARMADURAS & ESCUDOS",
    linhas: [
      { b: "01-02", n: "Armadura de chumbo", l: "Heróis de Arton", p: 223 },
      { b: "03-04", n: "Armadura de engenhoqueiro goblin", l: "Heróis de Arton", p: 223 },
      { b: "05-06", n: "Armadura de folhas", l: "Heróis de Arton", p: 223 },
      { b: "07-08", n: "Armadura de hussardo alado", l: "Heróis de Arton", p: 223 },
      { b: "09-10", n: "Armadura de justa", l: "Heróis de Arton", p: 223 },
      { b: "11", n: "Armadura de ossos", l: "Ameaças de Arton", p: 395 },
      { b: "12-13", n: "Armadura de pedra", l: "Heróis de Arton", p: 224 },
      { b: "14", n: "Armadura de quitina", l: "Ameaças de Arton", p: 395 },
      { b: "15-16", n: "Armadura sensual", l: "Heróis de Arton", p: 224 },
      { b: "17-20", n: "Brigantina", l: "Heróis de Arton", p: 224 },
      { b: "21-22", n: "Broquel", l: "Heróis de Arton", p: 224 },
      { b: "23-26", n: "Brunea", l: "Tormenta20", p: 154 },
      { b: "27-28", n: "Colete fora da lei", l: "Heróis de Arton", p: 226 },
      { b: "29-38", n: "Completa", l: "Tormenta20", p: 154 },
      { b: "39-42", n: "Cota de malha", l: "Tormenta20", p: 154 },
      { b: "43-44", n: "Cota de moedas", l: "Heróis de Arton", p: 226 },
      { b: "45-54", n: "Couraça", l: "Tormenta20", p: 154 },
      { b: "55-58", n: "Couro", l: "Tormenta20", p: 154 },
      { b: "59-64", n: "Couro batido", l: "Tormenta20", p: 154 },
      { b: "65", n: "Escudo de couro", l: "Ameaças de Arton", p: 395 },
      { b: "66", n: "Escudo de vime", l: "Heróis de Arton", p: 226 },
      { b: "67-74", n: "Escudo leve", l: "Tormenta20", p: 154 },
      { b: "75-82", n: "Escudo pesado", l: "Tormenta20", p: 154 },
      { b: "83-84", n: "Escudo torre", l: "Heróis de Arton", p: 226 },
      { b: "85-88", n: "Gibão de peles", l: "Tormenta20", p: 154 },
      { b: "89-92", n: "Loriga segmentada", l: "Tormenta20", p: 154 },
      { b: "93-98", n: "Meia armadura", l: "Tormenta20", p: 154 },
      { b: "99", n: "Sagna", l: "Heróis de Arton", p: 226 },
      { b: "100", n: "Veste de teia de aranha", l: "Ameaças de Arton", p: 395 },
    ]
  },
  bloco3: {
    titulo: "ESOTÉRICOS",
    linhas: [
      { b: "01-03", n: "Afiador solar", l: "Deuses de Arton", p: 51 },
      { b: "04-06", n: "Ankh solar", l: "Ameaças de Arton", p: 396 },
      { b: "07-10", n: "Báculo da retribuição", l: "Deuses de Arton", p: 51 },
      { b: "11-14", n: "Bolsa de pó", l: "Tormenta20", p: 159 },
      { b: "15-18", n: "Cajado arcano", l: "Tormenta20", p: 160 },
      { b: "19-22", n: "Cetro elemental", l: "Tormenta20", p: 160 },
      { b: "23-26", n: "Compasso mistico", l: "Heróis de Arton", p: 234 },
      { b: "27-30", n: "Contas de oração", l: "Deuses de Arton", p: 51 },
      { b: "31-34", n: "Costela de lich", l: "Tormenta20", p: 160 },
      { b: "35-38", n: "Dedo de ente", l: "Tormenta20", p: 160 },
      { b: "39-42", n: "Estola", l: "Deuses de Arton", p: 51 },
      { b: "43-46", n: "Flauta convocadora", l: "Heróis de Arton", p: 234 },
      { b: "47-50", n: "Frasco purificador", l: "Deuses de Arton", p: 51 },
      { b: "51-54", n: "Luva de ferro", l: "Tormenta20", p: 160 },
      { b: "55-58", n: "Mandala onírica", l: "Heróis de Arton", p: 234 },
      { b: "59-62", n: "Medalhão afiado", l: "Deuses de Arton", p: 51 },
      { b: "63-66", n: "Medalhão de prata", l: "Tormenta20", p: 160 },
      { b: "67-70", n: "Orbe cristalino", l: "Tormenta20", p: 160 },
      { b: "71-74", n: "Ostensório santificado", l: "Deuses de Arton", p: 51 },
      { b: "75-78", n: "Rede de almas", l: "Deuses de Arton", p: 52 },
      { b: "79-81", n: "Tomo de guerra", l: "Ameaças de Arton", p: 396 },
      { b: "82-84", n: "Tomo do rancor", l: "Ameaças de Arton", p: 396 },
      { b: "85-88", n: "Tomo hermético", l: "Tormenta20", p: 160 },
      { b: "89-92", n: "Turíbulo ungido", l: "Deuses de Arton", p: 52 },
      { b: "93-96", n: "Varinha arcana", l: "Tormenta20", p: 160 },
      { b: "97-100", n: "Varinha armamentista", l: "Heróis de Arton", p: 234 },
    ]
  },
};

/* ===== POÇÕES ===== */
var POCOES = [
  { b: "01", n: "Abençoar Alimentos (óleo)", v: 30, l: "Tormenta20", p: 178 },
  { b: "02", n: "Área Escorregadia (granada)", v: 30, l: "Tormenta20", p: 180 },
  { b: "03-04", n: "Arma Mágica (óleo)", v: 30, l: "Tormenta20", p: 181 },
  { b: "05", n: "Compreensão", v: 30, l: "Tormenta20", p: 184 },
  { b: "06-11", n: "Curar Ferimentos (2d8+2 PV)", v: 30, l: "Tormenta20", p: 189 },
  { b: "12-13", n: "Disfarce Ilusório", v: 30, l: "Tormenta20", p: 191 },
  { b: "14-15", n: "Escuridão (óleo)", v: 30, l: "Tormenta20", p: 193 },
  { b: "16-17", n: "Luz (óleo)", v: 30, l: "Tormenta20", p: 197 },
  { b: "18", n: "Névoa (granada)", v: 30, l: "Tormenta20", p: 200 },
  { b: "19", n: "Primor Atlético", v: 30, l: "Tormenta20", p: 201 },
  { b: "20", n: "Sono", v: 30, l: "Tormenta20", p: 207 },
  { b: "21-22", n: "Proteção Divina", v: 30, l: "Tormenta20", p: 202 },
  { b: "23-24", n: "Resistência a Energia", v: 30, l: "Tormenta20", p: 204 },
  { b: "25", n: "Suporte Ambiental", v: 30, l: "Tormenta20", p: 207 },
  { b: "26", n: "Tranca Arcana (óleo)", v: 30, l: "Tormenta20", p: 209 },
  { b: "27", n: "Visão Mística", v: 30, l: "Tormenta20", p: 211 },
  { b: "28", n: "Vitalidade Fantasma", v: 30, l: "Tormenta20", p: 211 },
  { b: "29", n: "Armadura Elemental", v: 30, l: "Heróis de Arton", p: 252 },
  { b: "30", n: "Desafio Corajoso", v: 30, l: "Heróis de Arton", p: 252 },
  { b: "31", n: "Discrição", v: 30, l: "Heróis de Arton", p: 253 },
  { b: "32", n: "Farejar Fortuna", v: 30, l: "Heróis de Arton", p: 254 },
  { b: "33", n: "Maaais Klunc", v: 30, l: "Heróis de Arton", p: 254 },
  { b: "34", n: "Ossos de Adamante", v: 30, l: "Heróis de Arton", p: 254 },
  { b: "35", n: "Punho de Mitral", v: 30, l: "Heróis de Arton", p: 254 },
  { b: "36", n: "Magia Dadivosa", v: 30, l: "Deuses de Arton", p: 62 },
  { b: "37", n: "Sigilo de Sszzaas", v: 30, l: "Deuses de Arton", p: 64 },
  { b: "38", n: "Sorriso da Fortuna", v: 30, l: "Deuses de Arton", p: 64 },
  { b: "39", n: "Toque de Megalokk", v: 30, l: "Deuses de Arton", p: 65 },
  { b: "40", n: "Voz da Razão", v: 30, l: "Deuses de Arton", p: 65 },
  { b: "41-42", n: "Escudo da Fé (aprimoramento para duração cena)", v: 120, l: "Tormenta20", p: 192 },
  { b: "43-44", n: "Alterar Tamanho", v: 270, l: "Tormenta20", p: 179 },
  { b: "45", n: "Aparência Perfeita", v: 270, l: "Tormenta20", p: 180 },
  { b: "46", n: "Armamento da Natureza (óleo)", v: 270, l: "Tormenta20", p: 181 },
  { b: "47-50", n: "Bola de Fogo (granada)", v: 270, l: "Tormenta20", p: 182 },
  { b: "51", n: "Camuflagem Ilusória", v: 270, l: "Tormenta20", p: 183 },
  { b: "52", n: "Concentração de Combate (aprimoramento para duração cena)", v: 270, l: "Tormenta20", p: 185 },
  { b: "53-56", n: "Curar Ferimentos (4d8+4 PV)", v: 270, l: "Tormenta20", p: 189 },
  { b: "57-58", n: "Físico Divino", v: 270, l: "Tormenta20", p: 193 },
  { b: "59", n: "Mente Divina", v: 270, l: "Tormenta20", p: 198 },
  { b: "60", n: "Metamorfose", v: 270, l: "Tormenta20", p: 198 },
  { b: "61-64", n: "Purificação", v: 270, l: "Tormenta20", p: 202 },
  { b: "65-66", n: "Velocidade", v: 270, l: "Tormenta20", p: 210 },
  { b: "67-68", n: "Vestimenta da Fé (óleo)", v: 270, l: "Tormenta20", p: 210 },
  { b: "69", n: "Voz Divina", v: 270, l: "Tormenta20", p: 211 },
  { b: "70-71", n: "Orientação (aprimoramento para duração cena; role o atributo afetado, sendo 1 = Força, 2 = Destreza e assim por diante)", v: 270, l: "Tormenta20", p: 200 },
  { b: "72", n: "Aura de Morte", v: 270, l: "Heróis de Arton", p: 252 },
  { b: "73", n: "Emular Magia", v: 270, l: "Heróis de Arton", p: 253 },
  { b: "74", n: "Punho de Mitral (aprimoramento para +2 em testes de ataque e margem de ameaça)", v: 270, l: "Heróis de Arton", p: 255 },
  { b: "75", n: "Viagem Onírica", v: 270, l: "Heróis de Arton", p: 255 },
  { b: "76", n: "Couraça de Allihanna (óleo)", v: 270, l: "Deuses de Arton", p: 60 },
  { b: "77", n: "Toque de Megalokk (aprimoramento para aumentar o dano das armas naturais em um passo e a margem de ameaça delas em +1 )", v: 480, l: "Deuses de Arton", p: 65 },
  { b: "78-79", n: "Arma Mágica (óleo; aprimoramento para bônus +3)", v: 750, l: "Tormenta20", p: 181 },
  { b: "80-81", n: "Proteção Divina (aprimoramento para bônus de +4)", v: 750, l: "Tormenta20", p: 202 },
  { b: "82", n: "Armadura Elemental (aprimoramento para 4d6 pontos de dano)", v: 750, l: "Heróis de Arton", p: 252 },
  { b: "83-88", n: "Curar Ferimentos (7d8+7 PV)", v: 1080, l: "Tormenta20", p: 189 },
  { b: "89-90", n: "Físico Divino (aprimoramento para três atributos)", v: 1080, l: "Tormenta20", p: 193 },
  { b: "91-92", n: "Invisibilidade (aprimoramento para duração cena)", v: 1080, l: "Tormenta20", p: 195 },
  { b: "93-94", n: "Pele de Pedra", v: 1080, l: "Tormenta20", p: 201 },
  { b: "95", n: "Potência Divina", v: 1080, l: "Tormenta20", p: 201 },
  { b: "96", n: "Voo", v: 1080, l: "Tormenta20", p: 211 },
  { b: "97", n: "Percepção Rubra (aprimoramento para aumentar bônus em +3)", v: 1080, l: "Deuses de Arton", p: 63 },
  { b: "98-100", n: "Bola de Fogo (granada; aprimoramento para 10d6 de dano)", v: 1470, l: "Tormenta20", p: 182 },
  { b: "101-110", n: "Curar Ferimentos (11d8+11 PV)", v: 3000, l: "Tormenta20", p: 189 },
  { b: "111-114", n: "Pele de Pedra (aprimoramento para pele de aço e RD 10)", v: 3000, l: "Tormenta20", p: 201 },
  { b: "115-116", n: "Premonição", v: 3000, l: "Tormenta20", p: 201 },
  { b: "117", n: "Viagem Onírica (aprimoramentos para falar e lançar magias)", v: 3000, l: "Heróis de Arton", p: 255 },
  { b: "118", n: "Potência Divina (aprimoramento para Força +6 e RD 15)", v: 6750, l: "Tormenta20", p: 201 },
  { b: "119", n: "Momento de Tormenta (granada; aprimoramento para +4 dados de dano do mesmo tipo)", v: 6750, l: "Ameaças de Arton", p: 404 },
  { b: "120", n: "Transformação em Dragão (aprimoramentos para atributos +4, asas, arma de mordida e dano de sopro de 12d6+12)", v: 28000, l: "Ameaças de Arton", p: 405 },
];

/* ===== SUPERIORES ===== */
var SUPERIORES = {
  bloco1: {
    titulo: "MELHORIAS DE ARMAS",
    linhas: [
      { b: "01-10", n: "Atroz*", l: "Tormenta20", p: 164 },
      { b: "11-12", n: "Banhada a ouro", l: "Tormenta20", p: 164 },
      { b: "13-20", n: "Certeira", l: "Tormenta20", p: 164 },
      { b: "21", n: "Conduíte", l: "Deuses de Arton", p: 54 },
      { b: "22-23", n: "Cravejada de gemas", l: "Tormenta20", p: 164 },
      { b: "24-31", n: "Cruel", l: "Tormenta20", p: 164 },
      { b: "32-33", n: "Discreta", l: "Tormenta20", p: 164 },
      { b: "34-38", n: "Equilibrada", l: "Tormenta20", p: 165 },
      { b: "39-42", n: "Farpada", l: "Heróis de Arton", p: 239 },
      { b: "43-44", n: "Guarda", l: "Heróis de Arton", p: 239 },
      { b: "45-48", n: "Harmonizada", l: "Tormenta20", p: 165 },
      { b: "49", n: "Incendiária", l: "Heróis de Arton", p: 239 },
      { b: "50-53", n: "Injeção alquímica", l: "Tormenta20", p: 165 },
      { b: "54-55", n: "Macabra", l: "Tormenta20", p: 165 },
      { b: "56-65", n: "Maciça", l: "Tormenta20", p: 165 },
      { b: "66-75", n: "Material especial**", l: "Tormenta20", p: 165 },
      { b: "76-79", n: "Mira telescópica", l: "Tormenta20", p: 166 },
      { b: "80-87", n: "Precisa", l: "Tormenta20", p: 166 },
      { b: "88-89", n: "Pressurizada", l: "Heróis de Arton", p: 240 },
      { b: "90-99", n: "Pungente*", l: "Tormenta20", p: 166 },
      { b: "100", n: "Usada", l: "Heróis de Arton", p: 240 },
    ]
  },
  bloco2: {
    titulo: "MELHORIAS DE ARMADURAS & ESCUDOS",
    linhas: [
      { b: "01-10", n: "Ajustada", l: "Tormenta20", p: 164 },
      { b: "11-14", n: "Balístico", l: "Heróis de Arton", p: 239 },
      { b: "15-18", n: "Banhada a ouro", l: "Tormenta20", p: 164 },
      { b: "19-22", n: "Cravejada de gemas", l: "Tormenta20", p: 164 },
      { b: "23-27", n: "Delicada", l: "Tormenta20", p: 164 },
      { b: "28-29", n: "Deslumbrante*", l: "Heróis de Arton", p: 239 },
      { b: "30-31", n: "Diligente", l: "Deuses de Arton", p: 54 },
      { b: "32-35", n: "Discreta", l: "Tormenta20", p: 164 },
      { b: "36-39", n: "Espinhos", l: "Tormenta20", p: 165 },
      { b: "40-43", n: "Injetora", l: "Heróis de Arton", p: 240 },
      { b: "44-47", n: "Inscrito", l: "Deuses de Arton", p: 54 },
      { b: "48-49", n: "Macabra", l: "Tormenta20", p: 165 },
      { b: "50-59", n: "Material especial**", l: "Tormenta20", p: 165 },
      { b: "60-64", n: "Polida", l: "Tormenta20", p: 166 },
      { b: "65-84", n: "Reforçada", l: "Tormenta20", p: 166 },
      { b: "85-95", n: "Selada", l: "Tormenta20", p: 166 },
      { b: "96-100", n: "Sob medida*", l: "Tormenta20", p: 166 },
    ]
  },
  bloco3: {
    titulo: "MELHORIAS DE ESOTÉRICOS",
    linhas: [
      { b: "01-03", n: "Banhado a ouro", l: "Tormenta20", p: 164 },
      { b: "04-18", n: "Canalizador", l: "Tormenta20", p: 164 },
      { b: "19-21", n: "Canônico", l: "Deuses de Arton", p: 54 },
      { b: "22-24", n: "Cravejado de gemas", l: "Tormenta20", p: 164 },
      { b: "25-28", n: "Discreto", l: "Tormenta20", p: 164 },
      { b: "29-43", n: "Energético", l: "Tormenta20", p: 165 },
      { b: "44-58", n: "Harmonizado", l: "Tormenta20", p: 165 },
      { b: "59-61", n: "Macabro", l: "Tormenta20", p: 165 },
      { b: "62-70", n: "Material especial**", l: "Tormenta20", p: 165 },
      { b: "71-80", n: "Poderoso", l: "Tormenta20", p: 166 },
      { b: "81-90", n: "Potencializador*", l: "Heróis de Arton", p: 240 },
      { b: "91-100", n: "Vigilante", l: "Tormenta20", p: 166 },
    ]
  },
};

/* ===== MÁGICOS (encantos) ===== */
var MAGICOS_ENCANTOS = {
  bloco1: {
    titulo: "ARMAS",
    linhas: [
      { b: "01", n: "Alvorada", l: "Heróis de Arton", p: 256 },
      { b: "02-05", n: "Ameaçadora", l: "Tormenta20", p: 335 },
      { b: "06", n: "Anátema", l: "Heróis de Arton", p: 256 },
      { b: "07-08", n: "Anticriatura", l: "Tormenta20", p: 335 },
      { b: "09", n: "Arremesso", l: "Tormenta20", p: 335 },
      { b: "10", n: "Assassina", l: "Tormenta20", p: 335 },
      { b: "11", n: "Brumosa", l: "Heróis de Arton", p: 256 },
      { b: "12", n: "Caçadora", l: "Tormenta20", p: 335 },
      { b: "13", n: "Cantante", l: "Heróis de Arton", p: 256 },
      { b: "14", n: "Ciclônica", l: "Heróis de Arton", p: 256 },
      { b: "15-18", n: "Congelante", l: "Tormenta20", p: 335 },
      { b: "19", n: "Conjuradora", l: "Tormenta20", p: 335 },
      { b: "20-23", n: "Corrosiva", l: "Tormenta20", p: 335 },
      { b: "24-25", n: "Crescente", l: "Heróis de Arton", p: 256 },
      { b: "26", n: "Cristalina", l: "Heróis de Arton", p: 256 },
      { b: "27", n: "Cronal*", l: "Heróis de Arton", p: 256 },
      { b: "28", n: "Cuidadora", l: "Heróis de Arton", p: 256 },
      { b: "29-30", n: "Dançarina", l: "Tormenta20", p: 335 },
      { b: "31-32", n: "Defensora", l: "Tormenta20", p: 335 },
      { b: "33", n: "Destruidora", l: "Tormenta20", p: 335 },
      { b: "34-35", n: "Dilacerante", l: "Tormenta20", p: 335 },
      { b: "36", n: "Drenante", l: "Tormenta20", p: 335 },
      { b: "37-40", n: "Elétrica", l: "Tormenta20", p: 335 },
      { b: "41", n: "Energética*", l: "Tormenta20", p: 335 },
      { b: "42-43", n: "Espreitadora", l: "Heróis de Arton", p: 256 },
      { b: "44-45", n: "Excruciante", l: "Tormenta20", p: 335 },
      { b: "46-49", n: "Flamejante", l: "Tormenta20", p: 335 },
      { b: "50-57", n: "Formidável", l: "Tormenta20", p: 336 },
      { b: "58-59", n: "Frenética", l: "Heróis de Arton", p: 256 },
      { b: "60", n: "Gárgula", l: "Heróis de Arton", p: 256 },
      { b: "61", n: "Horrenda", l: "Heróis de Arton", p: 256 },
      { b: "62", n: "Indignada", l: "Heróis de Arton", p: 256 },
      { b: "63", n: "Infestada", l: "Heróis de Arton", p: 256 },
      { b: "64", n: "Lancinante*", l: "Tormenta20", p: 336 },
      { b: "65-72", n: "Magnífica*", l: "Tormenta20", p: 336 },
      { b: "73", n: "Manáfaga", l: "Heróis de Arton", p: 256 },
      { b: "74-75", n: "Piedosa", l: "Tormenta20", p: 336 },
      { b: "76", n: "Profana", l: "Tormenta20", p: 336 },
      { b: "77", n: "Rebote", l: "Heróis de Arton", p: 256 },
      { b: "78", n: "Reflexiva", l: "Heróis de Arton", p: 257 },
      { b: "79", n: "Ressonante", l: "Heróis de Arton", p: 257 },
      { b: "80", n: "Sagrada", l: "Tormenta20", p: 336 },
      { b: "81-82", n: "Sanguinária", l: "Tormenta20", p: 336 },
      { b: "83", n: "Sepulcral", l: "Heróis de Arton", p: 257 },
      { b: "84", n: "Sombria", l: "Heróis de Arton", p: 257 },
      { b: "85", n: "Trovejante", l: "Tormenta20", p: 336 },
      { b: "86", n: "Tumular", l: "Tormenta20", p: 336 },
      { b: "87", n: "Vampírica", l: "Heróis de Arton", p: 257 },
      { b: "88-89", n: "Veloz", l: "Tormenta20", p: 336 },
      { b: "90", n: "Venenosa", l: "Tormenta20", p: 336 },
      { b: "91-100", n: "Arma específica", l: "Role na tabela abaixo", p: null },
    ]
  },
  bloco2: {
    titulo: "ARMADURAS & ESCUDOS",
    linhas: [
      { b: "01-02", n: "Abascanto", l: "Tormenta20", p: 338 },
      { b: "03-04", n: "Abençoado", l: "Tormenta20", p: 338 },
      { b: "05", n: "Abissal", l: "Heróis de Arton", p: 258 },
      { b: "06", n: "Acrobático", l: "Tormenta20", p: 338 },
      { b: "07-08", n: "Alado", l: "Tormenta20", p: 338 },
      { b: "09", n: "Ancorada*", l: "Heróis de Arton", p: 258 },
      { b: "10-11", n: "Animado**", l: "Tormenta20", p: 338 },
      { b: "12", n: "Anulador***", l: "Heróis de Arton", p: 258 },
      { b: "13", n: "Arbóreo", l: "Heróis de Arton", p: 258 },
      { b: "14-15", n: "Assustador", l: "Tormenta20", p: 338 },
      { b: "16", n: "Astuto", l: "Heróis de Arton", p: 258 },
      { b: "17", n: "Cáustica", l: "Tormenta20", p: 338 },
      { b: "18-27", n: "Defensor", l: "Tormenta20", p: 338 },
      { b: "28", n: "Densa*", l: "Heróis de Arton", p: 258 },
      { b: "29", n: "Égide", l: "Heróis de Arton", p: 258 },
      { b: "30", n: "Enraizada*", l: "Heróis de Arton", p: 258 },
      { b: "31", n: "Escorregadio", l: "Tormenta20", p: 338 },
      { b: "32-33", n: "Esmagador**", l: "Tormenta20", p: 339 },
      { b: "34", n: "Esmérico", l: "Heróis de Arton", p: 258 },
      { b: "35-36", n: "Estígio***", l: "Heróis de Arton", p: 258 },
      { b: "37", n: "Etéreo", l: "Heróis de Arton", p: 259 },
      { b: "38-39", n: "Fantasmagórico", l: "Tormenta20", p: 339 },
      { b: "40-43", n: "Fortificado", l: "Tormenta20", p: 339 },
      { b: "44", n: "Gélido", l: "Tormenta20", p: 339 },
      { b: "45", n: "Geomântico", l: "Heróis de Arton", p: 259 },
      { b: "46-55", n: "Guardião***", l: "Tormenta20", p: 339 },
      { b: "56-57", n: "Hipnótico", l: "Tormenta20", p: 339 },
      { b: "58", n: "Ilusório", l: "Tormenta20", p: 339 },
      { b: "59", n: "Incandescente", l: "Tormenta20", p: 339 },
      { b: "60-64", n: "Invulnerável", l: "Tormenta20", p: 339 },
      { b: "65", n: "Ligeira*", l: "Heróis de Arton", p: 259 },
      { b: "66-67", n: "Luminescente", l: "Heróis de Arton", p: 259 },
      { b: "68-72", n: "Opaco", l: "Tormenta20", p: 339 },
      { b: "73", n: "Prístino", l: "Heróis de Arton", p: 259 },
      { b: "74-78", n: "Protetor", l: "Tormenta20", p: 339 },
      { b: "79", n: "Purificador", l: "Heróis de Arton", p: 259 },
      { b: "80-81", n: "Reanimador", l: "Heróis de Arton", p: 259 },
      { b: "82-83", n: "Refletor", l: "Tormenta20", p: 339 },
      { b: "84", n: "Relampejante", l: "Tormenta20", p: 339 },
      { b: "85", n: "Reluzente", l: "Tormenta20", p: 339 },
      { b: "86", n: "Replicante", l: "Heróis de Arton", p: 259 },
      { b: "87", n: "Resiliente", l: "Heróis de Arton", p: 259 },
      { b: "88", n: "Sombrio", l: "Tormenta20", p: 339 },
      { b: "89", n: "Vórtice", l: "Heróis de Arton", p: 259 },
      { b: "90", n: "Zeloso", l: "Tormenta20", p: 339 },
      { b: "91-100", n: "Item específico", l: "Role na tabela abaixo", p: null },
    ]
  },
  bloco3: {
    titulo: "ESOTÉRICOS",
    linhas: [
      { b: "01-02", n: "Abafador", l: "Heróis de Arton", p: 260 },
      { b: "03-12", n: "Bélico", l: "Heróis de Arton", p: 260 },
      { b: "13-16", n: "Caridoso", l: "Heróis de Arton", p: 260 },
      { b: "17-20", n: "Chocante", l: "Heróis de Arton", p: 260 },
      { b: "21-30", n: "Clemente", l: "Heróis de Arton", p: 260 },
      { b: "31-32", n: "Contido", l: "Heróis de Arton", p: 260 },
      { b: "33-34", n: "Embusteiro", l: "Heróis de Arton", p: 260 },
      { b: "35-36", n: "Emergencial", l: "Heróis de Arton", p: 260 },
      { b: "37-40", n: "Encadeado", l: "Heróis de Arton", p: 260 },
      { b: "41-42", n: "Escultor", l: "Heróis de Arton", p: 260 },
      { b: "43-44", n: "Frugal", l: "Heróis de Arton", p: 261 },
      { b: "45-48", n: "Glacial", l: "Heróis de Arton", p: 261 },
      { b: "49-50", n: "Imperioso", l: "Heróis de Arton", p: 261 },
      { b: "51-52", n: "Implacável*", l: "Heróis de Arton", p: 261 },
      { b: "53-54", n: "Incriminador", l: "Heróis de Arton", p: 261 },
      { b: "55-61", n: "Inflamável", l: "Heróis de Arton", p: 261 },
      { b: "62-65", n: "Inquisidor", l: "Heróis de Arton", p: 261 },
      { b: "66-69", n: "Insistente", l: "Heróis de Arton", p: 261 },
      { b: "70-71", n: "Khalmyrita", l: "Heróis de Arton", p: 261 },
      { b: "72-81", n: "Majestoso*", l: "Heróis de Arton", p: 261 },
      { b: "82-83", n: "Nímbico", l: "Heróis de Arton", p: 261 },
      { b: "84", n: "Pulverizante*", l: "Heróis de Arton", p: 261 },
      { b: "85", n: "Retaliador", l: "Heróis de Arton", p: 261 },
      { b: "86-87", n: "Sanguessuga", l: "Heróis de Arton", p: 261 },
      { b: "88", n: "Traiçoeiro", l: "Heróis de Arton", p: 261 },
      { b: "89-90", n: "Verdugo", l: "Heróis de Arton", p: 261 },
      { b: "91-100", n: "Esotérico específico", l: "Role na tabela abaixo", p: null },
    ]
  },
};

/* ===== MÁGICOS — ACESSÓRIOS ===== */
var MAGICOS_ACESSORIOS = {
  bloco1: {
    titulo: "ACESSÓRIOS MENORES",
    linhas: [
      { b: "01", n: "Algibeira mordedora", v: 1000, l: "Heróis de Arton", p: 263 },
      { b: "02", n: "Elixir da mente dividida", v: 1500, l: "Heróis de Arton", p: 265 },
      { b: "03", n: "Papiro das estrelas", v: 1500, l: "Heróis de Arton", p: 267 },
      { b: "04", n: "Anel do sustento", v: 3000, l: "Tormenta20", p: 342 },
      { b: "05-07", n: "Bainha mágica", v: 3000, l: "Tormenta20", p: 342 },
      { b: "08-09", n: "Corda da escalada", v: 3000, l: "Tormenta20", p: 343 },
      { b: "10", n: "Ferraduras da velocidade", v: 3000, l: "Tormenta20", p: 344 },
      { b: "11-12", n: "Garrafa da fumaça eterna", v: 3000, l: "Tormenta20", p: 344 },
      { b: "13-15", n: "Gema da luminosidade", v: 3000, l: "Tormenta20", p: 344 },
      { b: "16-18", n: "Manto élfico", v: 3000, l: "Tormenta20", p: 345 },
      { b: "19-21", n: "Mochila de carga", v: 3000, l: "Tormenta20", p: 345 },
      { b: "22-23", n: "Amuleto da visão etérea", v: 3000, l: "Heróis de Arton", p: 263 },
      { b: "24-25", n: "Cinturão do trobo", v: 3000, l: "Heróis de Arton", p: 264 },
      { b: "26-27", n: "Elixir da eternidade", v: 3000, l: "Heróis de Arton", p: 265 },
      { b: "28-29", n: "Pérola da nulificação", v: 3000, l: "Heróis de Arton", p: 267 },
      { b: "30-31", n: "Saco dos ventos silenciosos", v: 3000, l: "Heróis de Arton", p: 267 },
      { b: "32-36", n: "Brincos da sagacidade", v: 4500, l: "Tormenta20", p: 342 },
      { b: "37-41", n: "Luvas da delicadeza", v: 4500, l: "Tormenta20", p: 344 },
      { b: "42-46", n: "Manoplas da força do ogro", v: 4500, l: "Tormenta20", p: 344 },
      { b: "47-50", n: "Manto da resistência", v: 4500, l: "Tormenta20", p: 344 },
      { b: "51-55", n: "Manto do fascínio", v: 4500, l: "Tormenta20", p: 344 },
      { b: "56-60", n: "Pingente da sensatez", v: 4500, l: "Tormenta20", p: 345 },
      { b: "61-65", n: "Torque do vigor", v: 4500, l: "Tormenta20", p: 345 },
      { b: "66", n: "Monóculo da franqueza", v: 4500, l: "Heróis de Arton", p: 266 },
      { b: "67-68", n: "Chapéu do disfarce", v: 6000, l: "Tormenta20", p: 343 },
      { b: "69", n: "Flauta fantasma", v: 6000, l: "Tormenta20", p: 344 },
      { b: "70-71", n: "Lanterna da revelação", v: 6000, l: "Tormenta20", p: 344 },
      { b: "72-73", n: "Algibeira provedora", v: 6000, l: "Heróis de Arton", p: 263 },
      { b: "74-75", n: "Gaiola dos arcanos", v: 6000, l: "Heróis de Arton", p: 266 },
      { b: "76-77", n: "Lâmpada da ilusão impecável", v: 6000, l: "Heróis de Arton", p: 266 },
      { b: "78-79", n: "Pena da criação", v: 6000, l: "Heróis de Arton", p: 267 },
      { b: "80-81", n: "Corda da resignação", v: 7500, l: "Heróis de Arton", p: 265 },
      { b: "82-86", n: "Anel da proteção", v: 9000, l: "Tormenta20", p: 342 },
      { b: "87", n: "Anel do escudo mental", v: 9000, l: "Tormenta20", p: 342 },
      { b: "88", n: "Pingente da saúde", v: 9000, l: "Tormenta20", p: 345 },
      { b: "89", n: "Coroa de flores", v: 9000, l: "Deuses de Arton", p: 55 },
      { b: "90", n: "Jarro das profundezas", v: 9000, l: "Deuses de Arton", p: 58 },
      { b: "91", n: "Escrivaninha consagrada", v: 9000, l: "Deuses de Arton", p: 58 },
      { b: "92", n: "Anel da proteção mental", v: 9000, l: "Heróis de Arton", p: 263 },
      { b: "93", n: "Berço das fadas", v: 9000, l: "Heróis de Arton", p: 263 },
      { b: "94", n: "Chapéu dos truques infinitos", v: 9000, l: "Heróis de Arton", p: 264 },
      { b: "95", n: "Cinto da leveza graciosa", v: 9000, l: "Heróis de Arton", p: 264 },
      { b: "96", n: "Cristal da voz silenciosa", v: 9000, l: "Heróis de Arton", p: 265 },
      { b: "97", n: "Cristal do tempo célere", v: 9000, l: "Heróis de Arton", p: 265 },
      { b: "98", n: "Ocarina da melodia distante", v: 9000, l: "Heróis de Arton", p: 266 },
      { b: "99", n: "Olhos do corvo", v: 9000, l: "Heróis de Arton", p: 266 },
      { b: "100", n: "Pergaminho da verdade cósmica", v: 9000, l: "Heróis de Arton", p: 267 },
    ]
  },
  bloco2: {
    titulo: "ACESSÓRIOS MÉDIOS",
    linhas: [
      { b: "01", n: "Anel de telecinesia", v: 10500, l: "Tormenta20", p: 342 },
      { b: "02", n: "Bola de cristal", v: 10500, l: "Tormenta20", p: 342 },
      { b: "03", n: "Caveira maldita", v: 10500, l: "Tormenta20", p: 343 },
      { b: "04", n: "Instrumento da alegria", v: 10500, l: "Deuses de Arton", p: 57 },
      { b: "05", n: "Ampulheta da harmonia temporal", v: 10500, l: "Heróis de Arton", p: 263 },
      { b: "06", n: "Amuleto do amparo", v: 10500, l: "Heróis de Arton", p: 263 },
      { b: "07", n: "Caixa dos ecos perdidos", v: 10500, l: "Heróis de Arton", p: 264 },
      { b: "08", n: "Colar da perseverança", v: 10500, l: "Heróis de Arton", p: 264 },
      { b: "09", n: "Colar do tirano", v: 10500, l: "Heróis de Arton", p: 265 },
      { b: "10", n: "Óculos da revelação", v: 10500, l: "Heróis de Arton", p: 266 },
      { b: "11", n: "Colar das bolas de fogo", v: 12000, l: "Heróis de Arton", p: 265 },
      { b: "12", n: "Sandálias de Valkaria", v: 12000, l: "Heróis de Arton", p: 267 },
      { b: "13", n: "Véu diáfano", v: 13500, l: "Deuses de Arton", p: 57 },
      { b: "14", n: "Botas aladas", v: 15000, l: "Tormenta20", p: 342 },
      { b: "15", n: "Botas inquietas", v: 15000, l: "Deuses de Arton", p: 59 },
      { b: "16", n: "Pira póstera", v: 15000, l: "Deuses de Arton", p: 59 },
      { b: "17", n: "Anel do pacto oneroso", v: 15000, l: "Heróis de Arton", p: 263 },
      { b: "18", n: "Botas do andarilho das sombras", v: 15000, l: "Heróis de Arton", p: 263 },
      { b: "19", n: "Cálice das marés", v: 15000, l: "Heróis de Arton", p: 264 },
      { b: "20", n: "Cinto dos caminhos cruzados", v: 15000, l: "Heróis de Arton", p: 264 },
      { b: "21", n: "Pedra da passagem", v: 15000, l: "Heróis de Arton", p: 267 },
      { b: "22", n: "Pingente da dor partilhada", v: 15000, l: "Heróis de Arton", p: 267 },
      { b: "23-26", n: "Braceletes de bronze", v: 16500, l: "Tormenta20", p: 342 },
      { b: "27", n: "Capa nebulosa", v: 16500, l: "Heróis de Arton", p: 264 },
      { b: "28", n: "Espelho do outro lado", v: 18000, l: "Heróis de Arton", p: 265 },
      { b: "29-30", n: "Gema da purificação", v: 18000, l: "Heróis de Arton", p: 266 },
      { b: "31-32", n: "Máscara da raposa", v: 18000, l: "Heróis de Arton", p: 266 },
      { b: "33-36", n: "Anel da energia", v: 21000, l: "Tormenta20", p: 342 },
      { b: "37-40", n: "Anel da vitalidade", v: 21000, l: "Tormenta20", p: 342 },
      { b: "41-42", n: "Anel de invisibilidade", v: 21000, l: "Tormenta20", p: 342 },
      { b: "43-44", n: "Braçadeiras do arqueiro", v: 21000, l: "Tormenta20", p: 342 },
      { b: "45-46", n: "Brincos de Marah", v: 21000, l: "Tormenta20", p: 343 },
      { b: "47-48", n: "Faixas do pugilista", v: 21000, l: "Tormenta20", p: 344 },
      { b: "49-50", n: "Manto da aranha", v: 21000, l: "Tormenta20", p: 344 },
      { b: "51-52", n: "Vassoura voadora", v: 21000, l: "Tormenta20", p: 345 },
      { b: "53-54", n: "Símbolo abençoado", v: 21000, l: "Tormenta20", p: 345 },
      { b: "55", n: "Colar de presas", v: 21000, l: "Deuses de Arton", p: 57 },
      { b: "56", n: "Vestido noturno", v: 21000, l: "Deuses de Arton", p: 58 },
      { b: "57", n: "Anel da beleza ilusória", v: 21000, l: "Heróis de Arton", p: 263 },
      { b: "58", n: "Bastão do sonhador", v: 21000, l: "Heróis de Arton", p: 263 },
      { b: "59", n: "Colar da fúria monstruosa", v: 21000, l: "Heróis de Arton", p: 264 },
      { b: "60", n: "Coroa da floresta sussurrante", v: 21000, l: "Heróis de Arton", p: 265 },
      { b: "61", n: "Espelho da verdade", v: 21000, l: "Heróis de Arton", p: 265 },
      { b: "62", n: "Instrumentos da celeridade", v: 22500, l: "Heróis de Arton", p: 266 },
      { b: "63", n: "Máscara do predador", v: 22500, l: "Heróis de Arton", p: 266 },
      { b: "64-65", n: "Frigideira do chef anão", v: 24000, l: "Heróis de Arton", p: 266 },
      { b: "66", n: "Gema da santificação", v: 24000, l: "Heróis de Arton", p: 266 },
      { b: "67", n: "Cubo armadilha", v: 25000, l: "Deuses de Arton", p: 56 },
      { b: "68", n: "Caldeirão da vida", v: 25000, l: "Deuses de Arton", p: 57 },
      { b: "69-72", n: "Amuleto da robustez", v: 25500, l: "Tormenta20", p: 342 },
      { b: "73-74", n: "Botas velozes", v: 25500, l: "Tormenta20", p: 342 },
      { b: "75-78", n: "Cinto da força do gigante", v: 25500, l: "Tormenta20", p: 343 },
      { b: "79-82", n: "Coroa majestosa", v: 25500, l: "Tormenta20", p: 344 },
      { b: "83-86", n: "Estola da serenidade", v: 25500, l: "Tormenta20", p: 344 },
      { b: "87", n: "Manto do morcego", v: 25500, l: "Tormenta20", p: 344 },
      { b: "88-91", n: "Pulseiras da celeridade", v: 25500, l: "Tormenta20", p: 345 },
      { b: "92-95", n: "Tiara da sapiência", v: 25500, l: "Tormenta20", p: 345 },
      { b: "96-97", n: "Argolas místicas", v: 25500, l: "Deuses de Arton", p: 59 },
      { b: "98", n: "Bastão da grande harmonia", v: 25500, l: "Heróis de Arton", p: 263 },
      { b: "99", n: "Coroa da majestade distorcida", v: 25500, l: "Heróis de Arton", p: 265 },
      { b: "100", n: "Bracelete do coração vivaz", v: 27000, l: "Heróis de Arton", p: 264 },
    ]
  },
  bloco3: {
    titulo: "ACESSÓRIOS MAIORES",
    linhas: [
      { b: "01-02", n: "Elmo do teletransporte", v: 30000, l: "Tormenta20", p: 344 },
      { b: "03-04", n: "Gema da telepatia", v: 30000, l: "Tormenta20", p: 344 },
      { b: "05-06", n: "Gema elemental", v: 30000, l: "Tormenta20", p: 344 },
      { b: "07-11", n: "Manual da saúde corporal", v: 30000, l: "Tormenta20", p: 345 },
      { b: "12-16", n: "Manual do bom exercício", v: 30000, l: "Tormenta20", p: 345 },
      { b: "17-21", n: "Manual dos movimentos precisos", v: 30000, l: "Tormenta20", p: 345 },
      { b: "22-26", n: "Medalhão de Lena", v: 30000, l: "Tormenta20", p: 345 },
      { b: "27-31", n: "Tomo da compreensão", v: 30000, l: "Tormenta20", p: 345 },
      { b: "32-36", n: "Tomo da liderança e influência", v: 30000, l: "Tormenta20", p: 345 },
      { b: "37-41", n: "Tomo dos grandes pensamentos", v: 30000, l: "Tormenta20", p: 345 },
      { b: "42-44", n: "Anel da chama dançante", v: 30000, l: "Heróis de Arton", p: 263 },
      { b: "45-46", n: "Chapéu pensador", v: 30000, l: "Heróis de Arton", p: 264 },
      { b: "47-48", n: "Cinto da flecha veloz", v: 30000, l: "Heróis de Arton", p: 264 },
      { b: "49-50", n: "Gema da profanação", v: 30000, l: "Heróis de Arton", p: 266 },
      { b: "51-53", n: "Tomo da técnica definitiva", v: 30000, l: "Heróis de Arton", p: 267 },
      { b: "54-55", n: "Tapeçaria da guerra", v: 35000, l: "Deuses de Arton", p: 55 },
      { b: "56-57", n: "Braceletes da amizade intensa", v: 36000, l: "Heróis de Arton", p: 264 },
      { b: "58", n: "Cilício vivo", v: 37000, l: "Deuses de Arton", p: 55 },
      { b: "59", n: "Coração corrompido", v: 45000, l: "Deuses de Arton", p: 55 },
      { b: "60-61", n: "Coração do inverno", v: 45000, l: "Heróis de Arton", p: 265 },
      { b: "62-63", n: "Tomo dos companheiros", v: 45000, l: "Heróis de Arton", p: 267 },
      { b: "64-65", n: "Anel refletor", v: 51000, l: "Tormenta20", p: 342 },
      { b: "66-67", n: "Cinto do campeão", v: 51000, l: "Tormenta20", p: 343 },
      { b: "68-71", n: "Colar guardião", v: 51000, l: "Tormenta20", p: 343 },
      { b: "72-73", n: "Estatueta animista", v: 51000, l: "Tormenta20", p: 344 },
      { b: "74-75", n: "Anel da liberdade", v: 60000, l: "Tormenta20", p: 342 },
      { b: "76-77", n: "Tapete voador", v: 60000, l: "Tormenta20", p: 345 },
      { b: "78-79", n: "Chave dos planos", v: 60000, l: "Heróis de Arton", p: 264 },
      { b: "80-81", n: "Cinto da desmaterialização", v: 60000, l: "Heróis de Arton", p: 264 },
      { b: "82-85", n: "Braceletes de ouro", v: 64500, l: "Tormenta20", p: 342 },
      { b: "86-87", n: "Espelho da oposição", v: 75000, l: "Tormenta20", p: 344 },
      { b: "88-91", n: "Robe do arquimago", v: 90000, l: "Tormenta20", p: 345 },
      { b: "92-93", n: "Ossos dracônicos", v: 90000, l: "Deuses de Arton", p: 56 },
      { b: "94-95", n: "Orbe das tempestades", v: 97500, l: "Tormenta20", p: 345 },
      { b: "96-97", n: "Braçadeiras da força do colosso", v: 120000, l: "Heróis de Arton", p: 264 },
      { b: "98-99", n: "Anel da regeneração", v: 150000, l: "Tormenta20", p: 342 },
      { b: "100", n: "Espelho do aprisionamento", v: 150000, l: "Tormenta20", p: 344 },
    ]
  },
};

/* ===== RIQUEZAS (valor) ===== */
var RIQUEZAS = [
  { menor: [1, 25], media: null, maior: null, valor: "4d4 (10)", exemplo: "0,5 espaço: ágata trincada, anel de hematita, bule de chá com gravações em prata, 1d4+1 soldadinhos de chumbo do Exército do Reinado, jarro de mel, prato de bronze, tapeçaria simples sem moldura, tinta de tecido suficiente para uma roupa; 1 espaço: caixa com velas aromáticas, estandarte em algodão de um nobre menor, kobold de pelúcia em tamanho natural, roldana de ferro; 2 espaços: barrilete de óleo cru, espantalho imitando um hynne nobre, rolo de algodão tecido, tela para pintura; 5 espaços: barril de farinha ou gaiola com galinhas." },
  { menor: [26, 40], media: null, maior: null, valor: "1d4x10 (25)", exemplo: "0,5 espaço: colar de presas de bulette, livreto de poesia bucaneira, quartzo rosa, topázio; 1 espaço: ânfora de prata com símbolo de Marah (vale o dobro em um templo da deusa), caixa de tabaco, rolo de linho, urna de sais aromáticos (pode ser usada como ingrediente para preparados), saco com penas de hipossauro; 2 espaços: conjunto de talheres de prata, jarro de especiarias, como canela, gorad, pimenta ou sal; 5 espaços: candelabro de bronze, colchão de palha de boa qualidade; —: vaca leiteira (irá acompanhá-lo se você for treinado em Adestramento)" },
  { menor: [41, 55], media: [1, 10], maior: null, valor: "2d4x10 (50)", exemplo: "0,5 espaço: ampulheta, arreios de prata, barra de gorad, bracelete de ouro finamente trabalhado, cadeado de latão de boa qualidade, leque de bambu e seda, garrafa com água das profundezas do Mar Negro (supostamente possui propriedades mágicas); 1 espaço: bengala de ébano com uma cabeça de serpente de marfim, estatueta de osso entalhado, frutas exóticas (estragam em 2d4 dias), lamparina de ouro (vale o dobro para um devoto de Azgher), livro de crônicas roramarianas, livro de receitas campeiras de Namalkah, molde para fabricar velas, rolo de seda 2 espaço: brazeiro de latão decorado, cobertor para montaria, couro curtido de um burafonte, vaso de prata." },
  { menor: [56, 70], media: [11, 30], maior: null, valor: "4d6x10 (140)", exemplo: "0,5 espaço: ametista, cartas de um nobre falecido (seus descendentes podem pagar o dobro), frasco de tinta allavir, pente de madeira Tollon, pérola branca, suspensórios elegantes; 1 espaço: caixa com 5 pares de meias de seda, cálice de prata com gemas de lápis-lazúli, estojo com sinete e apetrechos burocráticos (vale o dobro para o proprietário original), lingote de prata, sapatilha élfica confortável, tiara sinuosa própria para uma medusa, traje de festa exclusivo (concede +2 em Diplomacia durante a primeira cena em que for usado); 2 espaços: alvo para disparos sofisticado (treinar nele fornece +1 em Pontaria até o fim da aventura, mas o destrói), bloco de gelo das Uivantes (derrete em 1d6+3 dias), estatueta de uma cocatriz com olhos de madrepérola; 5 espaços: tapeçaria grande e bem-feita de lã; 20 espaços: porta de madeira maciça finamente entalhada." },
  { menor: [71, 85], media: [31, 50], maior: [1, 5], valor: "1d6x100 (350)", exemplo: "0,5 espaço: alexandrita, pérola negra, peruca de crina de pégaso; 1 espaço: caleidoscópio de bronze com imagens doheritas, espada cerimonial ornada com prata e gema negra no cabo, toga tapistana com barra bordada em ouro, pente de prata com pedras preciosas, roda de queijo de seiva de galhada (rende 12 fatias; cada uma recupera 1d4+1 PV), sapatos de dança em couro de serpe; 2 espaços: relógio de parede kliren; 5 espaços: cadeira de madeira Tollon, cavalo de balanço com crina de verdade; 10 espaços: conjunto de velas de um galeão; —: carruagem (pode ser puxada por um animal de tração ou arrastada por um personagem como um item que ocupa 20 espaços)." },
  { menor: [86, 95], media: [51, 65], maior: [6, 15], valor: "2d6x100 (700)", exemplo: "0,5 espaço: baralho de Wyrt com tinta de ouro, bracelete banhado em adamante, condecoração militar da Guerra Artoniana; 1 espaço: escultura de vidro feito com areia de Halak-Tur, estatueta de Valkaria em prata azulada, pente em forma de dragão com olhos de gema vermelha, máscara teatral de marfim com pedras preciosas, réplica do machado Zakharin (portá-lo é crime no Reinado), vestido digno de uma princesa; 2 espaços: telescópio portátil; 5 espaços: barril de cerveja fina de Doherimm, harpa de madeira exótica com ornamentos de zircão e marfim; 10 espaços: tronco de madeira Tollon." },
  { menor: [96, 99], media: [66, 80], maior: [16, 25], valor: "2d8x100 (900)", exemplo: "0,5 espaço: brinco com uma joia de aço-rubi, opala negra, tapa-olho com um olho falso de safira; 1 espaço: luva bordada e adornada com gemas, pingente de opala vermelha com corrente de ouro; 2 espaços: gaiola de prata para falcoaria, lingote de ouro, pintura antiga; 5 espaços: barril de especiarias de Moreania; —: carroça cheia de mercadorias comuns (pode ser puxada por um animal de tração ou arrastada por um personagem como um item que ocupa 20 espaços)." },
  { menor: [100, 100], media: [81, 90], maior: [26, 40], valor: "4d10x100 (2.200)", exemplo: "0,5 espaço: esmeralda verde, pingente de safira; 1 espaço: caixinha de música de ouro, ovo de grifo (com tempo e cuidado, pode ser transformado em um parceiro grifo iniciante), tornozeleira com gemas; 2 espaços: manto bordado em veludo e seda com inúmeras pedras preciosas; 5 espaços: berço de madeira Tollon com detalhes em ouro, chafariz de mármore para fonte de jardim, conjunto de taças de cristal em caixote; 20 espaços: coluna de mármore em estilo neogórdio." },
  { menor: null, media: [91, 95], maior: [41, 60], valor: "6d12x100 (3.900)", exemplo: "0,5 espaços: anel de prata e safira, correntinha com pequenas pérolas rosas, diamante branco, pingente de ouro com um topázio em forma de Marah; 1 espaço: espelho feito na Pondsmânia (adiciona traços feéricos ao reflexo do usuário); 2 espaços: miniatura mecânica de um dragão feita por um inventor renomado, tábua de granito com reprodução da Tarvica em letras de ouro, vestido digno de uma rainha; 5 espaços: ídolo de ouro puro maciço, quadro élfico em estilo sobrenaturalista; 100 espaços: bloco de mármore bruto." },
  { menor: null, media: [96, 99], maior: [61, 75], valor: "2d10x1.000 (11.000)", exemplo: "0,5 espaço: anel de ouro e rubi, diamante vermelho; 1 espaço: tiara de mitral cravejada de rubis; 2 espaços: conjunto de taças de ouro decoradas com esmeraldas; 5 espaços: busto de Tanna-Toh esculpido por um artista famoso, globo de Arton com pedras preciosas marcando os pontos de interesse conhecidos; 10 espaços: quadro do arquimago Vectorius em tamanho natural; 20 espaços: piano em madeira Tollon com cordas de mitral e teclas de marfim de Galrasia, estátua dourada de Klunk." },
  { menor: null, media: [100, 100], maior: [76, 85], valor: "6d8x1.000 (27.000)", exemplo: "1 espaço: coroa de ouro adornada com centenas de gemas que pertenceu a um antigo monarca; 2 espaço: baú de mitral com coleção de diamantes, tapeçaria da Tormenta em estilo grigoriano (observá-la fornece 1 PM temporário para devotos de Aharadak uma vez por dia); 5 espaço: estatueta de gelo eterno com uma essência elemental agitada em seu interior; 20 espaços: meteorito de adamante bruto, sino de catedral de ouro maciço." },
  { menor: null, media: null, maior: [86, 95], valor: "1d10x10.000 (55.000)", exemplo: "1 espaço: elmo de matéria vermelha com detalhes em rubis e turmalinas; 10 espaços: altar religioso em granito e onix com inscrições em ouro, sarcófago de ouro cravejado de gemas; 20 espaços: arca de madeira reforçada repleta de lingotes de prata e ouro e pedras preciosas de vários tipos; —: carruagem de luxo em madeira Tollon banhada a ouro com detalhes em metais finos e pedras preciosas (pode ser puxada por um animal de tração ou arrastada por um personagem como um item que ocupa 20 espaços)." },
  { menor: null, media: null, maior: [96, 100], valor: "4d12x10.000 (260.000)", exemplo: "20 espaços: estátua titanoteica em aventurina de uma divindade do Panteão; —: uma sala forrada de moedas (mover todo esse dinheiro exige trabalhadores e carroças, ou outra ideia por parte dos jogadores, além de atrair a atenção de bandidos, coletores de impostos e aproveitadores de vários tipos)." },
];

/* ===== RIQUEZAS — ESPAÇOS (1d20) ===== */
var RIQUEZAS_ESPACOS = [
  { d: [1, 4], espacos: 0.5, desc: "Um item muito pequeno ou leve, como um anel, um par de brincos ou uma gema." },
  { d: [5, 8], espacos: 1.0, desc: "Um item comum, como um cálice, uma estatueta ou um par de braceletes." },
  { d: [9, 12], espacos: 2.0, desc: "Um item volumoso ou pesado, como uma arma de duas mãos ou um baú." },
  { d: [13, 15], espacos: 5.0, desc: "Um item muito volumoso ou pesado, como uma armadura completa ou um barril." },
  { d: [16, 17], espacos: 10.0, desc: "Um item extremamente volumoso ou pesado, como um quadro que ocupa uma parede inteira ou um busto de pedra." },
  { d: [18, 19], espacos: 20.0, desc: "Um item mais volumoso ou pesado que uma pessoa, como uma arca repleta de moedas ou uma estátua de pedra." },
  { d: [20, 20], espacos: 100.0, desc: "Algo tão volumoso ou pesado que só pode ser carregado por várias pessoas e/ou veículos, como uma coleção de estátuas em tamanho real." },
];